version: "3.0"
services:
  ethereum:
    image: trufflesuite/ganache-cli:latest
    container_name: ethereum
    ports:
      - "8545:8545"
    volumes:
      - "ethereum-db:/ethereum/ethereum-db"
    working_dir: /ethereum
    command: ganache --deterministic --accounts 2 --db ./ethereum-db

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - './keycloak/keycloak-themes:/opt/bitnami/keycloak/themes'
      - './keycloak/keycloak-realms:/opt/bitnami/keycloak/data/import'
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: "true"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: keycloak-postgresql
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak

  keycloak-postgresql:
    image: docker.io/bitnami/postgresql:latest
    container_name: keycloak-postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - 'keycloak-db:/bitnami/postgresql'

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - "mongo-db:/data/db"
    command: mongod --dbpath /data/db

  bus:
    image: rabbitmq:3.7.7-management
    container_name: bus
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
    command: rabbitmq-server

volumes:
  keycloak-db:
    driver: local
  ethereum-db:
    driver: local
  mongo-db:
    driver: local
