NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/org2-ca-7054-org2-ca.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/org2-ca-7054-org2-ca.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/org2-ca-7054-org2-ca.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/org2-ca-7054-org2-ca.pem
    OrganizationalUnitIdentifier: orderer
